{
  "hash": "d4037a2cb01d4a2a79ea072a898fd077",
  "result": {
    "markdown": "---\ntitle: \"Textual Analysis\"\nauthor: \"Ethan Campbell\"\ndescription: \"First project\"\ndate: \"12/9/2022\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n# Introduction\n\nThe English Premier league has been one of the most talked about leagues in Soccer and it continues to provide world class soccer. However, underneath all of that excitement there is underlying meaning and messages that can help describe how a team reaches the top of the table. This study will be analyzing some of those underlying messages within match reports from 6 teams in the premier league. This will include 2 teams from the top, 2 teams from the middle, and 2 from the bottom. The reason I have selected this amount is to get a wider range of teams that are in different situations while keeping the study smaller. The goal of this research is to determine if each team utilizes different language over the season and how the results of each week impact these changes. To define this result we will webscrape each week of games from last season and the current 2022 season of matches. After this we will clean and merge this data together and get it ready for analysis. Following this will be dictionary methods which will include 3 different sentiment dictionaries and their comparison. I am using these to see how the teams are feeling and the level of structure they show throughout the season. After this we will move towards modeling and here we will partake in some LDA modeling which is being utilized to extract certain topics from the corpus. This will show the hidden topics within this data set and pull them forward into 6 topics. We are using 6 topics which is one for each team and this will show us a lot of data for each of them. This is followed by cosine similarity which will show me how similar these documents are to one another.\n\n# Hypothesis for project\n\n::: callout-note\n## Research Questions\n\nA. Does Premier League soccer teams language change over the course of the season?\n\nB. Does the language change in relation to the success of the season?\n:::\n\nThe hypothesis will be tested as follows:\n\n::: callout-tip\n## A.\n\nDo teams use more or less words over the course of the season?\n:::\n\n::: callout-tip\n## A.\n\nDo they grow more positive or negative over the course of the season?\n:::\n\n::: callout-tip\n## B.\n\nWhen a team performs well do they use more or less words to describe the match?\n:::\n\n::: callout-tip\n## B.\n\nDoes a teams sentiment change over the course of the season in relation to their success?\n:::\n\n# Analytic planning\n\nThis is the method that will be utilized in this study as described in the introduction.\n\n\n```{mermaid}\nflowchart LR\n  A[Web Scrape] --> B(Merge Data)\n  B --> C[Preprocess]\n  C --> D(Dictionary Analysis)\n  D --> E[Sentiment Dictionary]\n  E --> F[Bing,Afinn,Nrc]\n  F --> G[Compare/Visualize]\n  G --> H{Research Question}\n  C --> K[Models]\n  K --> L[LDA]\n  L --> M[Results/visuals]\n  M --> N{Research Question}\n```\n\n\n::: panel-tabset\n# Loading Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rvest)\nlibrary(tidyverse)\nlibrary(polite)\nlibrary(stringr)\nlibrary(preText)\nlibrary(quanteda)\nlibrary(quanteda.textplots)\nlibrary(tidytext)\nlibrary(tm)\nlibrary(SentimentAnalysis)\nlibrary(quanteda.dictionaries)\nlibrary(servr)\nlibrary(quanteda.textstats)\nlibrary(LDAvis)\nlibrary(text2vec)\nlibrary(hrbrthemes)\nlibrary(ggplot2)\nlibrary(ggthemes)\n```\n:::\n\n\n# Data Sources\n\nThere are 6 teams included in this study 2 from the top of the table 2 from the middle and 2 from the bottom. They are already in that order from top to bottom. Data needed to be web scraped from a page called match report. This page was located on each teams official website and this page included information about the match, statistics, and quotes from both the players and the managers. This data will include this current season and all of last season.\n\n[Arsenal Data](https://www.arsenal.com/news?field_article_arsenal_team_value=men&revision_information=&page=1)\n\n[Manchester City Data](https://www.mancity.com/news/mens)\n\n[Newcastle United Data](https://www.nufc.co.uk/matches/first-team/#results)\n\n[Everton Data](https://www.evertonfc.com/results)\n\n[Leicester Data](https://www.lcfc.com/matches/reports)\n\n[West Ham United Data](https://www.whufc.com/fixture/list/713)\n\n# Web Scraping/Tidying data\n\nHere is the beginning of the web scraping process. I was unable to find a way to make the web scraper search for one object then proceed to the next page where you could then scrape whats inside. For the time being I decided to manually web scrape the information. The tidying process is the real issue as there are many unwanted variables inside. For example there are a lot of /n's. Each team has a unique webscraping process so I created a function for each team to one webscrape the data and the perform some cleaning on the data. This was mostly successful however, I still ran into some issues where the data wouldn't quite clean the way I wanted. For example, the arsenal data had to be ran through the cleaning function twice to remove certain extra factors despite being in the cleaning function. This will require me to do more thorough cleaning as the research continues. There were a lot of issues in the cleaning process one of the major ones is with West Ham. The issues is that the only part that would pull all the text includes an image and since I am using html_text it is converted to the textual data which is a bunch of random special characters. This required a ton of cleaning to try and pull all of them out.\n\n::: {.callout-note collapse=\"true\"}\n## Arsenal Webscrape\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## The function is working at reading in the data however. parts of the cleaning process are failing and I am thinking this is because I am not specifying the create values\n\n# I need to remove punct, capitalization, stopwords like (the, a ',') finish repeating the process to all teams and adjusting the function until it grabs every single problem once this is complete we should be able to tokenize then corpus and work with the data\n\nWeb_scrape_function_Arsenal <- function(url,css,data) { # creating function to repeat web scrape\n  url <- read_html(url)\ncss <- (\".article-body\")\ndata <- url %>%\n  html_node(css = css) %>%\n  html_text2()\n}\n\ntidy_function <- function(data){data <- str_replace_all(data, \"\\n\", \"####\") %>%\n  str_replace_all(\"/n\", \"####\") %>%\n  str_remove_all(\"/n\") %>%\n  str_remove_all(\"\\n\") %>%\n  str_remove_all(\" - \") %>%\n  str_replace_all(\"'\\'\", \"#\") %>%\n  str_replace_all(\"[0-9] of [0-9]To buy official Arsenal pictures visit Arsenal Pics\", \"#\") %>%\n  str_remove(\"WHAT HAPPENED\") %>%\n  str_remove_all(\"[0-9] of 42To buy official Arsenal pictures visit Arsenal Pics\") %>%\n  str_remove_all(\"[0-9] of 29To buy official Arsenal pictures visit Arsenal Pics\") %>%\n  str_remove_all(\"[0-9] of 45To buy official Arsenal pictures visit Arsenal Pics\") %>%\n  str_remove_all(\"[0-9] of 38To buy official Arsenal pictures visit Arsenal Pics\") %>%\n  str_remove_all(\"[0-9] of 32To buy official Arsenal pictures visit Arsenal Pics\") %>%\n  str_remove_all(\"[0-9] of 36To buy official Arsenal pictures visit Arsenal Pics\") %>%\n  str_remove(\"Play videoWatch Arsenal video online05:24Highlights | Crystal Palace 0-2 Arsenal - bitesize\") %>%\n  str_remove(\"111111111122222222223333333333444\") %>%\n  str_remove(\"111111111122222222223333333\") %>%\n  str_remove(\"11111111112222222222\") %>%\n  str_remove_all(\"\\\\(\") %>%\n  str_remove_all(\"\\\\)\") %>%\n  str_replace_all(\"||\", \"#\") %>%\n  str_remove_all(\"'Play videoWatch Arsenal video online02:17Mikel Arteta post-match interview | Crystal Palace 0-2 Arsenal | Premier LeagueArteta: \\'\") %>%\n  str_remove_all(\"\\\"read everything from his press conferencePlay videoWatch Arsenal video online02:07William Saliba post-match interview || Premier LeagueSaliba:\") %>%\n  str_remove_all(\"buy official arsenal pictures visit arsenal pics\") %>%\n  str_remove_all(\"#\") %>%\n  unlist()\n}\n\n# Running the tidy function twice to clean up certain parts that are getting missed the first time for some reason and this is a temporary fix.\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Aug-05/crystal-palace-0-2-arsenal-match-report\"\nMatch_1 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_1 <- tidy_function(Match_1)\nMatch_1 <- tidy_function(Match_1)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Aug-13/arsenal-4-2-leicester-city-match-report\"\nMatch_2 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_2 <- tidy_function(Match_2)\nMatch_2 <- tidy_function(Match_2)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-bournemouth-odegaard-saliba-jesus\"\nMatch_3 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_3 <- tidy_function(Match_3)\nMatch_3 <- tidy_function(Match_3)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-fulham-odegaard-gabriel\"\nMatch_4 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_4 <- tidy_function(Match_4)\nMatch_4 <- tidy_function(Match_4)\nArsenal_url <- \"https://www.arsenal.com/match-report-aston-villa-premier-league-martinelli-jesus\"\nMatch_5 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_5 <- tidy_function(Match_5)\nMatch_5 <- tidy_function(Match_5)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Sep-04/manchester-united-3-1-arsenal-match-report\"\nMatch_6 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_6 <- tidy_function(Match_6)\nMatch_6 <- tidy_function(Match_6)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-brentford-saliba-jesus-vieira\"\nMatch_7 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_7 <- tidy_function(Match_7)\nMatch_7 <- tidy_function(Match_7)\n# Arsenal 2021 season\n\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Jul-28/arsenal-4-1-watford-match-report\"\nMatch_1_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_1_2021 <- tidy_function(Match_1_2021)\nMatch_1_2021 <- tidy_function(Match_1_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Aug-01/arsenal-1-2-chelsea-match-report\"\nMatch_2_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_2_2021 <- tidy_function(Match_2_2021)\nMatch_2_2021 <- tidy_function(Match_2_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Aug-08/tottenham-hotspur-1-0-arsenal-match-report\"\nMatch_3_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_3_2021 <- tidy_function(Match_3_2021)\nMatch_3_2021 <- tidy_function(Match_3_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Aug-13/brentford-fc-2-0-arsenal-match-report\"\nMatch_4_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_4_2021 <- tidy_function(Match_4_2021)\nMatch_4_2021 <- tidy_function(Match_4_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Aug-22/arsenal-0-2-chelsea-match-report\"\nMatch_5_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_5_2021 <- tidy_function(Match_5_2021)\nMatch_5_2021 <- tidy_function(Match_5_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Aug-28/manchester-city-5-0-arsenal-match-report\"\nMatch_6_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_6_2021 <- tidy_function(Match_6_2021)\nMatch_6_2021 <- tidy_function(Match_6_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Sep-11/arsenal-1-0-norwich-city-match-report\"\nMatch_7_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_7_2021 <- tidy_function(Match_7_2021)\nMatch_7_2021 <- tidy_function(Match_7_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Sep-18/burnley-0-1-arsenal-match-report\"\nMatch_8_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_8_2021 <- tidy_function(Match_8_2021)\nMatch_8_2021 <- tidy_function(Match_8_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Sep-26/arsenal-3-1-tottenham-hotspur-match-report\"\nMatch_9_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_9_2021 <- tidy_function(Match_9_2021)\nMatch_9_2021 <- tidy_function(Match_9_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Oct-02/brighton-0-0-arsenal-match-report\"\nMatch_10_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_10_2021 <- tidy_function(Match_10_2021)\nMatch_10_2021 <- tidy_function(Match_10_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Oct-18/arsenal-2-2-crystal-palace-match-report\"\nMatch_11_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_11_2021 <- tidy_function(Match_11_2021)\nMatch_11_2021 <- tidy_function(Match_11_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Oct-22/arsenal-3-1-aston-villa-match-report\"\nMatch_12_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_12_2021 <- tidy_function(Match_12_2021)\nMatch_12_2021 <- tidy_function(Match_12_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Oct-30/leicester-city-0-2-arsenal-match-report\"\nMatch_13_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_13_2021 <- tidy_function(Match_13_2021)\nMatch_13_2021 <- tidy_function(Match_13_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Nov-07/arsenal-1-0-watford-match-report\"\nMatch_14_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_14_2021 <- tidy_function(Match_14_2021)\nMatch_14_2021 <- tidy_function(Match_14_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Nov-20/liverpool-4-0-arsenal-match-report\"\nMatch_15_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_15_2021 <- tidy_function(Match_15_2021)\nMatch_15_2021 <- tidy_function(Match_15_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Nov-27/arsenal-2-0-newcastle-united-match-report\"\nMatch_16_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_16_2021 <- tidy_function(Match_16_2021)\nMatch_16_2021 <- tidy_function(Match_16_2021)\nArsenal_url <- \"https://www.arsenal.com/arsenal-manchester-united-match-report-premier-league\"\nMatch_17_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_17_2021 <- tidy_function(Match_17_2021)\nMatch_17_2021 <- tidy_function(Match_17_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Dec-06/everton-2-1-arsenal-match-report\"\nMatch_18_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_18_2021 <- tidy_function(Match_18_2021)\nMatch_18_2021 <- tidy_function(Match_18_2021)\nArsenal_url <- \"https://www.arsenal.com/arsenal-southampton-match-report-premier-league-lacazette\"\nMatch_19_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_19_2021 <- tidy_function(Match_19_2021)\nMatch_19_2021 <- tidy_function(Match_19_2021)\nArsenal_url <- \"https://www.arsenal.com/arsenal-west-ham-match-report-premier-league-martinelli-smith-rowe\"\nMatch_20_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_20_2021 <- tidy_function(Match_20_2021)\nMatch_20_2021 <- tidy_function(Match_20_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Dec-18/leeds-1-4-arsenal-match-report\"\nMatch_21_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_21_2021 <- tidy_function(Match_21_2021)\nMatch_21_2021 <- tidy_function(Match_21_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2021-Dec-26/norwich-city-0-5-arsenal-match-report\"\nMatch_22_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_22_2021 <- tidy_function(Match_22_2021)\nMatch_22_2021 <- tidy_function(Match_22_2021)\nArsenal_url <- \"https://www.arsenal.com/arsenal-manchester-city-report-xhaka-gabriel-premier-league\"\nMatch_23_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_23_2021 <- tidy_function(Match_23_2021)\nMatch_23_2021 <- tidy_function(Match_23_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-burnley-match-report-emirates-stadium\"\nMatch_24_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_24_2021 <- tidy_function(Match_24_2021)\nMatch_24_2021 <- tidy_function(Match_24_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Feb-10/wolves-0-1-arsenal-match-report\"\nMatch_25_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_25_2021 <- tidy_function(Match_25_2021)\nMatch_25_2021 <- tidy_function(Match_25_2021)\nArsenal_url <- \"https://www.arsenal.com/match-report-emile-smith-rowe-bukayo-saka-premier-league-southampton\"\nMatch_26_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_26_2021 <- tidy_function(Match_26_2021)\nMatch_26_2021 <- tidy_function(Match_26_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Feb-24/arsenal-2-1-wolves-match-report-0\"\nMatch_27_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_27_2021 <- tidy_function(Match_27_2021)\nMatch_27_2021 <- tidy_function(Match_27_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-watford-odegaard-saka-martinelli\"\nMatch_28_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_28_2021 <- tidy_function(Match_28_2021)\nMatch_28_2021 <- tidy_function(Match_28_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-leicester-city-thomas-partey-alexandre-lacazette\"\nMatch_29_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_29_2021 <- tidy_function(Match_29_2021)\nMatch_29_2021 <- tidy_function(Match_29_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Mar-16/arsenal-0-2-liverpool-match-report\"\nMatch_30_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_30_2021 <- tidy_function(Match_30_2021)\nMatch_30_2021 <- tidy_function(Match_30_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-bukayo-saka-aston-villa-top-four\"\nMatch_31_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_31_2021 <- tidy_function(Match_31_2021)\nMatch_31_2021 <- tidy_function(Match_31_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Apr-04/crystal-palace-3-0-arsenal-match-report\"\nMatch_32_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_32_2021 <- tidy_function(Match_32_2021)\nMatch_32_2021 <- tidy_function(Match_32_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-brighton-martin-odegaard-emirates-stadium\"\nMatch_33_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_33_2021 <- tidy_function(Match_33_2021)\nMatch_33_2021 <- tidy_function(Match_33_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-Apr-16/southampton-1-0-arsenal-match-report\"\nMatch_34_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_34_2021 <- tidy_function(Match_34_2021)\nMatch_34_2021 <- tidy_function(Match_34_2021)\nArsenal_url <- \"https://www.arsenal.com/match-report-premier-league-chelsea-nketiah-smith-rowe-saka\"\nMatch_35_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_35_2021 <- tidy_function(Match_35_2021)\nMatch_35_2021 <- tidy_function(Match_35_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-manchester-united-saka-tavares-xhaka-ronaldo\"\nMatch_36_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_36_2021 <- tidy_function(Match_36_2021)\nMatch_36_2021 <- tidy_function(Match_36_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-west-ham-london-stadium\"\nMatch_37_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_37_2021 <- tidy_function(Match_37_2021)\nMatch_37_2021 <- tidy_function(Match_37_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-leeds-united-emirates-stadium-top-four-nketiah\"\nMatch_38_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_38_2021 <- tidy_function(Match_38_2021)\nMatch_38_2021 <- tidy_function(Match_38_2021)\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-tottenham-hotspur-top-four\"\nMatch_39_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_39_2021 <- tidy_function(Match_39_2021)\nMatch_39_2021 <- tidy_function(Match_39_2021)\nArsenal_url <- \"https://www.arsenal.com/fixture/arsenal/2022-May-16/newcastle-united-2-0-arsenal-match-report\"\nMatch_40_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_40_2021 <- tidy_function(Match_40_2021)\nMatch_40_2021 <- tidy_function(Match_40_2021)\n\nArsenal_url <- \"https://www.arsenal.com/premier-league-match-report-everton-mikel-arteta-emirates-stadium\"\nMatch_41_2021 <- Web_scrape_function_Arsenal(Arsenal_url)\nMatch_41_2021 <- tidy_function(Match_41_2021)\nMatch_41_2021 <- tidy_function(Match_41_2021)\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Manchester City Webscrape\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Manchester City data\n\nWeb_scrape_function_mancity <- function(url,css,data) { # creating function to repeat web scrape\n  url <- read_html(url)\ncss <- (\".article-body__article-text\")\ndata <- url %>%\n  html_node(css = css) %>%\n  html_text2()\ndata <- str_replace_all(data, \"\\n\", \"####\") %>%\n  str_replace_all(\"/n\", \"####\") %>%\n  str_remove_all(\"/n\") %>%\n  str_remove_all(\"\\n\") %>%\n  str_remove_all(\" - \") %>%\n  str_remove_all(\"\\\\(\") %>%\n  str_remove_all(\"\\\\)\") %>%\n  str_remove_all(\"#\") %>%\n  str_remove_all(\"'\\'\") %>%\n  gsub(pattern = \"\\\\W\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\b[A-z]\\\\b{1}\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\W\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\d\", replace = \" \", data) %>%\n  unlist()\n}\n\nmancity_url <- \"https://www.mancity.com/news/mens/west-ham-v-manchester-city-premier-league-match-report-63795480\"\nManc_1 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/man-city-bournemouth-premier-league-match-report-63795987\"\nManc_2 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/newcastle-v-manchester-city-match-report-63796690\"\nManc_3 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/man-city-crystal-palace-match-report-63797204\"\nManc_4 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-nottingham-forest-match-report-31-august-63797573\"\nManc_5 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/aston-villa-manchester-city-premier-league-match-report-63797816\"\nManc_6 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/wolves-manchester-city-away-premier-league-2022-match-report-63799002\"\nManc_7 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/tottenham-hotspur-v-manchester-city-match-report-63764635\"\nManc_1_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-norwich-premier-league-21-august-match-report-63765149\"\nManc_2_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-arsenal-premier-league-aug-28-match-report-63765746\"\nManc_3_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/leicester-man-city-match-report-premier-league-11-september-63766964\"\nManc_4_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-southampton-premier-league-match-report-63767564\"\nManc_5_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-wycombe-wanderers-match-report-21-september-63767846\"\nManc_6_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/chelsea-man-city-premier-league-63768172\"\nManc_7_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/liverpool-v-manchester-city-premier-league-match-report-63768869\"\nManc_8_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/man-city-burnley-premier-league-match-report-63769988\"\nManc_9_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/brighton-man-city-premier-league-match-report-63770611\"\nManc_10_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-crystal-palace-premier-league-match-report-30-october-63771197\"\nManc_11_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-united-city-derby-match-report-premier-league-63771797\"\nManc_12_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-everton-premier-league-match-report-63773091\"\nManc_13_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-west-ham-united-premier-league-28-nov-match-report-63773703\"\nManc_14_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/aston-villa-v-manchester-city-premier-league-match-report-63773986\"\nManc_15_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/watford-v-manchester-city-pl-match-report-4-december-63774234\"\nManc_16_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-wolves-premier-league-match-report-63774823\"\nManc_17_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-leeds-united-premier-league-match-report-63775100\"\nManc_18_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/newcastle-united-v-manchester-city-match-report-19-dec-63775518\"\nManc_19_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-leicester-premier-league-match-report-63776131\"\nManc_20_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/brentford-man-city-premier-league-match-report-63776395\"\nManc_21_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/arsenal-man-city-premier-league-match-report-63776627\"\nManc_22_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-chelsea-premier-league-match-report-63777838\"\nManc_23_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/southampton-v-manchester-city-premier-league-match-report-63778466\"\nManc_24_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-brentford-premier-league-match-report-63780029\"\nManc_25_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/norwich-manchester-city-premier-league-12-february-63780282\"\nManc_26_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-tottenham-match-report-63780885\"\nManc_27_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/everton-man-city-premier-league-match-report-63781486\"\nManc_28_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-manchester-united-premier-league-match-report-6-march-2022-63782178\"\nManc_29_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/crystal-palace-v-manchester-city-premier-league-match-report-1-63782881\"\nManc_30_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/burnley-manchester-city-premier-league-match-report-63784504\"\nManc_31_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/man-city-liverpool-premier-league-match-report-63785199\"\nManc_32_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-brighton-and-hove-albion-premier-league-match-report-63786059\"\nManc_33_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-watford-premier-league-match-report-63786322\"\nManc_34_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/leeds-united-v-manchester-city-premier-league-match-report-30-april-63786930\"\nManc_35_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-newcastle-united-premier-league-match-report-8-may-2022-63787619\"\nManc_36_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/wolves-v-manchester-city-premier-league-match-report-63787892\"\nManc_37_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/west-ham-man-city-premier-league-match-report-63788208\"\nManc_38_2021 <- Web_scrape_function_mancity(mancity_url)\n\nmancity_url <- \"https://www.mancity.com/news/mens/manchester-city-v-aston-villa-match-report-may-2022-63788826\"\nManc_39_2021 <- Web_scrape_function_mancity(mancity_url)\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## New Castle Webscrape\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# New Castle\n\n# New Castle United first match against nottingham forest\n# 1 rule for 1 bots crawl delay 5 seconds, scrapable\n\nbow(\"https://www.nufc.co.uk/matches/first-team/2022-23/newcastle-united-v-nottingham-forest/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<polite session> https://www.nufc.co.uk/matches/first-team/2022-23/newcastle-united-v-nottingham-forest/\n    User-agent: polite R package\n    robots.txt: 1 rules are defined for 1 bots\n   Crawl delay: 5 sec\n  The path is scrapable for this user-agent\n```\n:::\n\n```{.r .cell-code}\nWeb_scrape_function_Newcastle <- function(url,css,data) { # creating function to repeat web scrape\n  url <- read_html(url)\ncss <- (\".article__body\")\ndata <- url %>%\n  html_node(css = css) %>%\n  html_text2()\ndata <- str_replace_all(data, \"\\n\", \"####\") %>%\n  str_replace_all(\"/n\", \"####\") %>%\n  str_remove_all(\"/n\") %>%\n  str_remove_all(\"\\n\") %>%\n  str_remove_all(\" - \") %>%\n  str_remove_all(\"\\\\(\") %>%\n  str_remove_all(\"\\\\)\") %>%\n  str_remove_all(\"\\\"\") %>%\n  str_remove_all(\"#\") %>%\n  gsub(pattern = \"\\\\b[A-z]\\\\b{1}\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\W\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\d\", replace = \" \", data) %>%\n  unlist()\n}\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/newcastle-united-v-nottingham-forest/\"\nnc_1 <- Web_scrape_function_Newcastle(Newcastle_url)\n                       \nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/brighton-and-hove-albion-v-newcastle-united/\"\nnc_2 <- Web_scrape_function_Newcastle(Newcastle_url)\n                       \nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/newcastle-united-v-manchester-city/\"\nnc_3 <- Web_scrape_function_Newcastle(Newcastle_url)\n                       \nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/wolverhampton-wanderers-v-newcastle-united/\"\nnc_4 <- Web_scrape_function_Newcastle(Newcastle_url)\n                       \nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/liverpool-v-newcastle-united/\"\nnc_5 <- Web_scrape_function_Newcastle(Newcastle_url)\n                       \nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/newcastle-united-v-crystal-palace/\"\nnc_6 <- Web_scrape_function_Newcastle(Newcastle_url)\n                       \nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2022-23/newcastle-united-v-bournemouth/\"\nnc_7 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-west-ham-united/\"\nnc_1_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/aston-villa-v-newcastle-united/\"\nnc_2_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-southampton/\"\nnc_3_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/manchester-united-v-newcastle-united/\"\nnc_4_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-leeds-united/\"\nnc_5_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/watford-v-newcastle-united/\"\nnc_6_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/wolverhampton-wanderers-v-newcastle-united/\"\nnc_7_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-tottenham-hotspur/\"\nnc_8_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/crystal-palace-v-newcastle-united/\"\nnc_9_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-chelsea/\"\nnc_10_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/brighton-and-hove-albion-v-newcastle-united/\"\nnc_11_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-brentford/\"\nnc_12_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/arsenal-v-newcastle-united/\"\nnc_13_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-norwich-city/\"\nnc_14_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-burnley/\"\nnc_15_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/leicester-city-v-newcastle-united/\"\nnc_16_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/liverpool-v-newcastle-united/\"\nnc_17_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-manchester-city/\"\nnc_18_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-manchester-united/\"\nnc_19_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-watford/\"\nnc_20_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/leeds-united-v-newcastle-united/\"\nnc_21_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-everton/\"\nnc_22_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-aston-villa/\"\nnc_23_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/west-ham-united-v-newcastle-united/\"\nnc_24_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/brentford-v-newcastle-united/\"\nnc_25_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-brighton-and-hove-albion/\"\nnc_26_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/southampton-v-newcastle-united/\"\nnc_27_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/chelsea-v-newcastle-united/\"\nnc_28_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/everton-v-newcastle-united/\"\nnc_29_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/tottenham-hotspur-v-newcastle-united/\"\nnc_30_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-wolverhampton-wanderers/\"\nnc_31_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-leicester-city/\"\nnc_32_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-crystal-palace/\"\nnc_33_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/norwich-city-v-newcastle-united/\"\nnc_34_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-liverpool/\"\nnc_35_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/manchester-city-v-newcastle-united/\"\nnc_36_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/newcastle-united-v-arsenal/\"\nnc_37_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n\nNewcastle_url <- \"https://www.nufc.co.uk/matches/first-team/2021-22/burnley-v-newcastle-united/\"\nnc_38_2021 <- Web_scrape_function_Newcastle(Newcastle_url)\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Everton Webscrape\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Everton\n\n# Everton vs Chelsea\n# 1 rule for 1 bots crawl delay 5 seconds, scrapable\n\nbow(\"https://www.evertonfc.com/match/74913/everton-chelsea#report\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<polite session> https://www.evertonfc.com/match/74913/everton-chelsea#report\n    User-agent: polite R package\n    robots.txt: 1 rules are defined for 1 bots\n   Crawl delay: 5 sec\n  The path is scrapable for this user-agent\n```\n:::\n\n```{.r .cell-code}\nWeb_scrape_function_Everton <- function(url,css,data) { # creating function to repeat web scrape\n  url <- read_html(url)\ncss <- (\".article__body.mc-report__body.js-article-body\")\ndata <- url %>%\n  html_node(css = css) %>%\n  html_text2()\ndata <- str_replace_all(data, \"\\n\", \"####\") %>%\n  str_replace_all(\"/n\", \"####\") %>%\n  str_remove_all(\"/n\") %>%\n  str_remove_all(\"\\n\") %>%\n  str_remove_all(\" - \") %>%\n  str_remove_all(\"\\\\(\") %>%\n  str_remove_all(\"\\\\)\") %>%\n  str_remove_all(\"\\\"\") %>%\n  str_remove_all(\"#\") %>%\n  gsub(pattern = \"\\\\b[A-z]\\\\b{1}\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\W\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\d\", replace = \" \", data) %>%\n  unlist()\n}\n\nEverton_url <- \"https://www.evertonfc.com/match/74913/everton-chelsea#report\"\never_1 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/74922/aston-villa-everton#report\"\never_2 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/74933/everton-nottm-forest#report\"\never_3 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <-\"https://www.evertonfc.com/match/74943/brentford-everton#report\"\never_4 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/74955/leeds-everton#report\"\never_5 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/74965/everton-liverpool#report\"\never_6 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/74985/everton-west-ham#report\"\never_7 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66345/everton-southampton#report\"\never_1_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66356/leeds-everton#report\"\never_2_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66363/brighton-everton#report\"\never_3_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66376/everton-burnley#report\"\never_4_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66382/aston-villa-everton#report\"\never_5_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66396/everton-norwich#report\"\never_6_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66408/man-utd-everton#report\"\never_7_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66415/everton-west-ham#report\"\never_8_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66427/everton-watford#report\"\never_9_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66441/wolves-everton#report\"\never_10_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66447/everton-spurs#report\"\never_11_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66456/man-city-everton#report\"\never_12_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66463/brentford-everton#report\"\never_13_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66473/everton-liverpool#report\"\never_14_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66483/everton-arsenal#report\"\never_15_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66497/crystal-palace-everton#report\"\never_16_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66509/chelsea-everton#report\"\never_17_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66546/everton-brighton#report\"\never_18_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66558/norwich-everton#report\"\never_19_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66566/everton-aston-villa#report\"\never_20_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66580/newcastle-everton#report\"\never_21_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66585/everton-leeds#report\"\never_22_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66599/southampton-everton#report\"\never_23_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66607/everton-man-city#report\"\never_24_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66619/spurs-everton#report\"\never_25_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66627/everton-wolves#report\"\never_26_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66536/everton-newcastle#report\"\never_27_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66650/west-ham-everton#report\"\never_28_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66524/burnley-everton#report\"\never_29_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66655/everton-man-utd#report\"\never_30_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66513/everton-leicester#report\"\never_31_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66679/liverpool-everton#report\"\never_32_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66683/everton-chelsea#report\"\never_33_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66698/leicester-everton#report\"\never_34_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66640/watford-everton#report\"\never_35_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66703/everton-brentford#report\"\never_36_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66663/everton-crystal-palace#report\"\never_37_2021 <- Web_scrape_function_Everton(Everton_url)\n\nEverton_url <- \"https://www.evertonfc.com/match/66712/arsenal-everton#report\"\never_38_2021 <- Web_scrape_function_Everton(Everton_url)\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Leicester Webscrape\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Leicester against Brentford\n# 1 bot 1 rule scrapable 5 second crawl\nbow(\"https://www.lcfc.com/news/2729025/city-held-by-bees-in-premier-league-opener/featured\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<polite session> https://www.lcfc.com/news/2729025/city-held-by-bees-in-premier-league-opener/featured\n    User-agent: polite R package\n    robots.txt: 1 rules are defined for 1 bots\n   Crawl delay: 5 sec\n  The path is scrapable for this user-agent\n```\n:::\n\n```{.r .cell-code}\nWeb_scrape_function_Leicester <- function(url,css,data) { # creating function to repeat web scrape\n  url <- read_html(url)\ncss <- (\".featured-article__content\")\ndata <- url %>%\n  html_node(css = css) %>%\n  html_text2()\ndata <- str_replace_all(data, \"\\n\", \"####\") %>%\n  str_replace_all(\"/n\", \"####\") %>%\n  str_remove_all(\"/n\") %>%\n  str_remove_all(\"\\n\") %>%\n  str_remove_all(\" - \") %>%\n  str_remove_all(\"\\\\(\") %>%\n  str_remove_all(\"\\\\)\") %>%\n  str_remove_all(\"\\\"\") %>%\n  str_remove_all(\"#\") %>%\n  str_remove_all(\"More on this story. . . In Photos -\") %>%\n  gsub(pattern = \"\\\\b[A-z]\\\\b{1}\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\W\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\d\", replace = \" \", data) %>%\n  unlist()\n}\n\nLeicester_url <- \"https://www.lcfc.com/news/2729025/city-held-by-bees-in-premier-league-opener/featured\"\nlei_1 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2739798/foxes-fall-to-defeat-at-arsenal/featured\"\nlei_2 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2751347/saints-take-the-points-on-filbert-way/featured\"\nlei_3 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2762326/city-defeated-as-10man-chelsea-win-at-stamford-bridge/featured\"\nlei_4 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2774578/man-utd-defeat-for-leicester-on-matchday-five/featured\"\nlei_5 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2779658/city-beaten-away-to-brighton/featured\"\nlei_6 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2793845/leicester-lose-to-spurs-in-london/featured\"\nlei_7 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2217322/resolute-foxes-up--running-with-wolves-triumph/featured\"\nlei_1_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2230429/hammers-beat-10-man-city-in-london/featured\"\nlei_2_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2234788/vardy--albrighton-secure-norwich-success-for-leicester/featured\"\nlei_3_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2250306/leicester-narrowly-beaten-by-champions-man-city/featured\"\nlei_4_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2260914/leicester-edged-by-brighton-on-the-south-coast/featured\"\nlei_5_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2268672/a-point-apiece-for-leicester--burnley-on-filbert-way/featured\"\nlei_6_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2280501/leicester--palace-in-lively-sunday-stalemate/featured\"\nlei_7_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2290123/city-triumph-over-united-in-six-goal-thriller/featured\"\nlei_8_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2306064/three-wins-in-a-row-for-resolute-foxes-in-london/featured\"\nlei_9_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2314376/city-lose-out-to-arsenal-on-filbert-way/featured\"\nlei_10_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2342690/leicester--leeds-in-lively-elland-road-stalemate/featured\"\nlei_11_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2358864/leicester-suffer-chelsea-reverse-on-filbert-way/featured\"\nlei_12_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2374499/wintery-win-for-clinical-foxes/featured\"\nlei_13_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2384599/a-point-apiece-for-leicester--southampton-on-south-coast/featured\"\nlei_14_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2395677/villa-victorious-as-citys-unbeaten-run-ends/featured\"\nlei_15_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2412212/city-beat-newcastle-in-style/featured\"\nlei_16_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2427298/battling-foxes-beaten-by-leaders-man-city/featured\"\nlei_17_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2431258/resolute-foxes-dig-in-for-huge-liverpool-victory/featured\"\nlei_18_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2454413/spurs-strike-late-to-beat-city/featured\"\nlei_19_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2460104/foxes-denied-all-three-points-late-on/featured\"\nlei_20_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2479311/battling-foxes-beaten-at-anfield/featured\"\nlei_21_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2483971/city-held-by-west-ham-on-filbert-way/featured\"\nlei_22_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2495055/foxes-frustrated-by-defiant-wolves/featured\"\nlei_23_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2510398/foxes-dig-deep-to-win-in-lancashire/featured\"\nlei_24_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2514784/barnes-strike-the-difference-as-leicester-defeat-leeds/featured\"\nlei_25_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2530191/first-loss-in-five-for-leicester/featured\"\nlei_26_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2543012/thunderous-castagne--maddison-strikes-stun-brentford/featured\"\nlei_27_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2558138/city-settle-for-a-point-at-old-trafford/featured\"\nlei_28_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2570206/lookman-strikes--dewsbury-hall-stuns-in-palace-win/featured\"\nlei_29_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2578121/leicester-defeated-late-on-in-newcastle/featured\"\nlei_30_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2582262/late-richarlison-leveller-denies-leicester-three-points/featured\"\nlei_31_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2586312/no-breakthrough-as-city--villa-share-the-spoils/featured\"\nlei_32_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2599299/courageous-city-beaten-in-north-london/featured\"\nlei_33_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2609135/everton-reverse-for-leicester-on-filbert-way/featured\"\nlei_34_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2613820/landmark-vardy-brace-helps-city-defeat-norwich/featured\"\nlei_35_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2617291/foxes-humble-watford-at-vicarage-road/featured\"\nlei_36_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2623942/foxes-claim-point-in-stamford-bridge-battle/featured\"\nlei_37_2021 <- Web_scrape_function_Leicester(Leicester_url)\n\nLeicester_url <- \"https://www.lcfc.com/news/2627341/foxes-finish-eighth-with-convincing-saints-win/featured\"\nlei_38_2021 <- Web_scrape_function_Leicester(Leicester_url)\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## West Ham Webscrape\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWeb_scrape_function_WestHam <- function(url,css,data) { # creating function to repeat web scrape\n  url <- read_html(url)\ncss <- (\".m-article__content\")\ndata <- url %>%\n  html_node(css = css) %>%\n  html_text2()\ndata <- str_replace_all(data, \"\\n\", \"####\") %>%\n  str_replace_all(\"/n\", \"####\") %>%\n  str_remove_all(\"/n\") %>%\n  str_remove_all(\"\\n\") %>%\n  str_remove_all(\"\\\\[\") %>%\n  str_remove_all(\"\\\\*\") %>%\n  str_remove_all(\"\\\\{\") %>%\n  str_remove_all(\"\\\\}\") %>%\n  str_remove_all(\"\\\\><\") %>%\n  str_remove_all(\"\\\\/!]]\") %>%\n  str_remove_all(\"CDATA\") %>%\n  str_remove_all(\"\\\\/\") %>%\n  str_remove_all(\"blockquote\") %>%\n  str_remove_all(\"\\\\]]]]> ]]>\") %>%\n  str_remove_all(\"\\\\< < \") %>%\n  str_remove_all(\"\\\\<\") %>%\n  str_remove_all(\"pnthchild2\") %>%\n  str_remove_all(\"\\\\fontstyle\") %>%\n  str_remove_all(\"italic\") %>%\n  str_remove_all(\"\\\\]]><\") %>%\n  str_remove_all(\"blockquote\") %>%\n  str_remove_all(\"\\\\       0  \") %>%\n  str_remove_all(\"margin\") %>%\n  str_remove_all(\"16px\") %>%\n  str_remove_all(\"8px\") %>%\n  str_remove_all(\"borderleft\") %>%\n  str_remove_all(\"solid\") %>%\n  str_remove_all(\"black\") %>%\n  str_remove_all(\"boarderleft\") %>%\n  str_remove_all(\"      0   border-left 1px     pnth-child2  font-style   \") %>%\n  str_remove_all(\"\\\\/!]]>/\") %>%\n  str_remove_all(\"\\\\;\") %>%\n  str_remove_all(\"\\\\<!!\") %>%\n  str_remove_all(\"\\\\]]>\") %>%\n  str_remove_all(\"\\\\!\") %>%\n  str_remove_all(\"\\\\:\") %>%\n  str_remove_all(\"\\\\        0   borderleft 1px\") %>%\n  str_remove_all(\"\\\\--\") %>%\n  str_remove_all(\"\\\\<!/!\") %>%\n  str_remove_all(\"blockquote  margin 16px 0 16px 8px borderleft 1px solid black\") %>%\n  str_remove_all(\"\\\\    pnthchild2  fontstyle   ]]]]> \") %>%\n  str_remove_all(\"\\\\CDATA/\") %>%\n  str_remove_all(\"\\\\(\") %>%\n  str_remove_all(\"\\\\)\") %>%\n  str_remove_all(\"\\\"\") %>%\n  str_remove_all(\"#\") %>%\n  str_remove_all(\"More on this story. . . In Photos -\") %>%\n  gsub(pattern = \"\\\\b[A-z]\\\\b{1}\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\W\", replace = \" \", data) %>%\n  gsub(pattern = \"\\\\d\", replace = \" \", data) %>%\n  unlist()\n}\n\n# West ham will be slightly shorter since their website did not post match reports on certain games for some reason?? They also had very weird URL's that were different half the time.\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6472\"\nwh_1 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6464\"\nwh_2 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6452\"\nwh_3 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6450\"\nwh_4 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6436\"\nwh_5 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6428\"\nwh_6 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/fixture/view/6407\"\nwh_7 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/august/15-august/west-ham-united-roar-back-win-thrilling-opener-newcastle-united\"\nwh_1_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/august/23-august/west-ham-united-storm-top-premier-league-thumping-win-over\"\nwh_2_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/september/19-september/hammers-suffer-late-heartbreak-against-manchester-united\"\nwh_3_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/september/25-september/west-ham-united-stun-leeds-united-elland-road\"\nwh_4_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/october/03-october/late-goal-condemns-hammers-defeat-against-brentford\"\nwh_5_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/node/459620\"\nwh_6_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/node/459803\"\nwh_7_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/october/31-october/rampant-hammers-knock-four-villa-romp\"\nwh_8_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/november/07-november/west-ham-united-defeat-liverpool-move-third-premier-league\"\nwh_9_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-taste-defeat-wolves\"\nwh_10_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/node/460400\"\nwh_11_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/node/460430\"\nwh_12_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/articles/2021/december/04-december/west-ham-united-complete-superb-comeback-down-chelsea\"\nwh_13_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-held-burnley\"\nwh_14_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-suffer-derby-defeat-arsenal\"\nwh_15_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-edged-out-southampton\"\nwh_16_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/outstanding-hammers-see-out-year-style-against-watford\"\nwh_17_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/manuel-lanzini-double-west-ham-united-hold-crystal-palace\"\nwh_18_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/harrison-hat-trick-ends-west-ham-uniteds-winning-run\"\nwh_19_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-slip-late-defeat-manchester-united\"\nwh_20_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/bowen-strike-earns-hammers-win-over-watford\"\nwh_21_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/craig-dawson-strikes-late-earn-west-ham-united-point-leicester-city\"\nwh_22_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/west-ham-united-forced-settle-point-against-newcastle-united\"\nwh_23_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/birthday-boy-tomas-soucek-fires-west-ham-united-victory-over-wolves\"\nwh_24_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-edged-out-anfield\"\nwh_25_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/yarmolenko-strikes-hammers-beat-aston-villa\"\nwh_26_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-beaten-tottenham-hotspur\"\nwh_27_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/cresswell-and-bowen-goals-see-everton\"\nwh_28_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/west-ham-stumble-defeat-brentford\"\nwh_29_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/west-ham-frustrated-burnley\"\nwh_30_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/late-heartbreak-hammers-chelsea\"\nwh_31_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/arsenal-frustrate-west-ham-london-stadium\"\nwh_32_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/hammers-score-four-superb-norwich-city-win\"\nwh_33_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/bowen-double-and-fabianski-penalty-save-earn-heroic-point\"\nwh_34_2021 <- Web_scrape_function_WestHam(WestHam_url)\n\nWestHam_url <- \"https://www.whufc.com/news/brighton-deny-west-ham-top-six-finish\"\nwh_35_2021 <- Web_scrape_function_WestHam(WestHam_url)\n```\n:::\n\n:::\n\n# Preprocessing\n\nPreprocessing is where I gathered all of my data and created 1 major corpus called Prem.\n\n::: {.callout-note collapse=\"true\"}\n## Creating Objects\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First step is to make these character vectors into a corpus to use for preprocessing\n# Arsenal\nArsenal <- c(Match_1, Match_2, Match_3, Match_4, Match_5, Match_6, Match_7,Match_1_2021, Match_2_2021, Match_3_2021, Match_4_2021, Match_5_2021, Match_6_2021, Match_7_2021,Match_8_2021, Match_9_2021, Match_10_2021, Match_11_2021, Match_12_2021, Match_13_2021, Match_14_2021, Match_15_2021, Match_16_2021, Match_17_2021, Match_18_2021, Match_19_2021, Match_20_2021, Match_21_2021, Match_22_2021, Match_23_2021, Match_24_2021, Match_25_2021, Match_26_2021, Match_27_2021, Match_28_2021, Match_29_2021, Match_30_2021, Match_31_2021, Match_32_2021, Match_33_2021, Match_34_2021, Match_35_2021, Match_36_2021, Match_37_2021, Match_38_2021, Match_39_2021, Match_40_2021, Match_41_2021)\n\nArsenal <- gsub(pattern = \"\\\\b[s]\\\\b{1}\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"\\\\b[e]\\\\b{1}\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"\\\\W\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"\\\\d\", replace = \" \", Arsenal)\nArsenal <- str_remove_all(Arsenal, \"$ing\")\nArsenal <- gsub(pattern = \" e \", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"media\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"read\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \" t \", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \" https \", replace = \" \", Arsenal)\nArsenal <- str_replace_all(Arsenal, \"keep ing\", \"keeping\")\nArsenal <- gsub(pattern = \" com\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"\\\\www\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"\\\\wwwww\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"\\\\lwwwl\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \" re \", replace = \"are\", Arsenal)\nArsenal <- gsub(pattern = \"copyright arsenal football club plc permission use quotations article granted subject appropriate credit given arsenal source \", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \" copyright arsenal football club plc permission use quotations article granted subject appropriate credit given arsenal source \", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \" copyright arsenal football club plc permission use quotations article granted subject appropriate credit given arsenal source \", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"visit arsenal pics buy official arsenal pictures\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"buy official arsenal pictures visit arsenal pics\", replace = \" \", Arsenal)\nArsenal <- gsub(pattern = \"play videowatch arsenal video online\", replace = \" \", Arsenal)\nArsenal <- tolower(Arsenal)\nArsenal <- removeWords(Arsenal, stopwords())\nArsenal <- stripWhitespace(Arsenal)\n\n# man city\n\nManchester_City <- c(Manc_1, Manc_2, Manc_3, Manc_4, Manc_5, Manc_6, Manc_7, Manc_1_2021, Manc_2_2021, Manc_3_2021, Manc_4_2021, Manc_5_2021, Manc_6_2021, Manc_7_2021, Manc_8_2021, Manc_9_2021, Manc_10_2021, Manc_11_2021, Manc_12_2021, Manc_13_2021, Manc_14_2021, Manc_15_2021, Manc_16_2021, Manc_17_2021, Manc_18_2021, Manc_19_2021, Manc_20_2021, Manc_21_2021, Manc_22_2021, Manc_23_2021, Manc_24_2021, Manc_25_2021, Manc_26_2021, Manc_27_2021, Manc_28_2021, Manc_29_2021, Manc_30_2021, Manc_31_2021, Manc_32_2021, Manc_33_2021, Manc_34_2021, Manc_35_2021, Manc_36_2021, Manc_37_2021, Manc_38_2021, Manc_39_2021)\n                       \nManchester_City <- gsub(pattern = \"gf ga gd pts form arsenal arsenal wdwww manchester city man city lwwwl newcastle united newcastle wwwww last updated december context http schema org type table premier league view full table vjs poster background image url https www mancity com meta media p mf krx lufc match highlights templatesmatch highlights wide jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media p mf krx lufc match highlights templatesmatch highlights wide jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media p mf krx lufc match highlights templatesmatch highlights wide jpg width height mode crop important context https schema org type videoobject name leeds city brief highlights description leeds city brief highlights expires thumbnailurl https www mancity com meta media p mf krx lufc match highlights templatesmatch highlights wide jpg duration pt m s embedurl https www mancity com citytv mens leeds manchester city brief highlights uploaddate\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"As it standsPremier League  Team          GF GA GD Pts Form     Arsenal Arsenal                       WDWWW     Manchester City Man City                       LWWWL     Newcastle United Newcastle                      WWWWW Last updated    December                 context    http   schema org       type    Table     about    Premier League        View full tableStatzone\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \" w d \", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \" d l \", replace = \" \", Manchester_City)\nManchester_City <- str_replace_all(Manchester_City, \" w d l\", \" \")\nManchester_City <- str_replace(Manchester_City, \" ll \", \" \")\nManchester_City <- gsub(pattern = \" vjs poster background image url https www mancity com meta media ycgb yoc brighton city rodri png width height mode crop important media min width px vjs poster background image url https www mancity com meta media ycgb yoc brighton city rodri png width height mode crop important media min width px vjs poster background image url https www mancity com meta media ycgb yoc brighton city rodri png width height mode crop important context https schema org type videoobject name short highlights brighton city description short highlights brighton city expires thumbnailurl https www mancity com meta media ycgb yoc brighton city rodri png duration pt m s embedurl https www mancity com citytv mens brighton manchester city premier league short highlights uploaddate\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"SHOP THE PREMIER LEAGUE CHAMPIONS  RANGEA \", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"molineux uk vjs poster background image url https www mancity com meta media g tca h ewcastle_ x jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media g tca h ewcastle_ x jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media g tca h ewcastle_ x jpg width height mode crop important context https schema org type videoobject name city newcastle top five goals description city newcastle top five goals expires thumbnailurl https www mancity com meta media g tca h ewcastle_ x jpg duration pt m s embedurl https www mancity com citytv mens top five goals manchester city newcastle etihad uploaddate goals vital\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \" vjs poster background image url https www mancity com meta media dg z villa hlts wide jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media dg z villa hlts wide jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media dg z villa hlts wide jpg width height mode crop important context https schema org type videoobject name short highlights aston villa city description short highlights aston villa city expires thumbnailurl https www mancity com meta media dg z villa hlts wide jpg duration pt m s embedurl https www mancity com citytv mens aston villa manchester city premier league short uploaddate\" , replace = \" \", Manchester_City )\nManchester_City <- gsub(pattern = \" pic twitter com xwo jjk v optajoe optajoenovember vjs poster background image url https www mancity com meta media ejp v match_hlx _ jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media ejp v match_hlx _ jpg width height mode crop important media min width px vjs poster background image url https www mancity com meta media ejp v match_hlx _ jpg width height mode crop important context https schema org type videoobject name highlights manchester united city description highlights manchester united city expires thumbnailurl https www mancity com meta media ejp v match_hlx _ jpg duration pt m s embedurl https www mancity com citytv mens manchester united city premier league short uploaddate men team united city match stats reaction\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"read more\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"highlightsextended action\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"full match replaywatch\", replace =\" \", Manchester_City)\nManchester_City <- gsub(pattern = \"view more\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"match highlights\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"highlights\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"wdwww\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"lwwwl\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"wwwww\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \" t \", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \" https \", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"media\", replace = \" \", Manchester_City)\nManchester_City <- gsub(pattern = \"read\", replace = \" \", Manchester_City)\nManchester_City <- str_replace_all(Manchester_City, \" s e \", \" \")\nManchester_City <- tolower(Manchester_City)\nManchester_City <- removeWords(Manchester_City, stopwords())\nManchester_City <- stripWhitespace(Manchester_City)\n# Newcastle united\n\nNewcastle_United <- c(nc_1, nc_2, nc_3, nc_4, nc_5, nc_6, nc_7, nc_1_2021, nc_2_2021, nc_3_2021, nc_4_2021, nc_5_2021, nc_6_2021, nc_7_2021, nc_8_2021, nc_9_2021, nc_10_2021, nc_11_2021, nc_12_2021, nc_13_2021, nc_14_2021, nc_15_2021, nc_16_2021, nc_17_2021, nc_18_2021, nc_19_2021, nc_20_2021, nc_21_2021, nc_22_2021, nc_23_2021, nc_24_2021, nc_25_2021, nc_26_2021, nc_27_2021, nc_28_2021, nc_29_2021, nc_30_2021, nc_31_2021, nc_32_2021, nc_33_2021, nc_34_2021, nc_35_2021, nc_36_2021, nc_37_2021, nc_38_2021)\n\nNewcastle_United <- gsub(pattern = \"\\\\W\", replace = \" \", Newcastle_United)\nNewcastle_United <- gsub(pattern = \"\\\\d\", replace = \" \", Newcastle_United)\nNewcastle_United <- gsub(pattern = \" t \", replace = \" \", Newcastle_United)\nNewcastle_United <- gsub(pattern = \" https \", replace = \" \", Newcastle_United)\nNewcastle_United <- gsub(pattern = \"media\", replace = \" \", Newcastle_United)\nNewcastle_United <- gsub(pattern = \"read\", replace = \" \", Newcastle_United)\nNewcastle_United <- tolower(Newcastle_United)\nNewcastle_United <- removeWords(Newcastle_United, stopwords())\nNewcastle_United <- stripWhitespace(Newcastle_United)\n# Everton\n\nEverton <- c(ever_1, ever_2, ever_3, ever_4, ever_5, ever_6, ever_7, ever_1_2021, ever_2_2021, ever_3_2021, ever_4_2021, ever_5_2021, ever_6_2021, ever_7_2021, ever_8_2021, ever_9_2021, ever_10_2021, ever_11_2021, ever_12_2021, ever_13_2021, ever_14_2021, ever_15_2021, ever_16_2021, ever_17_2021, ever_18_2021, ever_19_2021, ever_20_2021, ever_21_2021, ever_22_2021, ever_23_2021, ever_24_2021, ever_25_2021, ever_26_2021, ever_27_2021, ever_28_2021, ever_29_2021, ever_30_2021, ever_31_2021, ever_32_2021, ever_33_2021, ever_34_2021, ever_35_2021, ever_36_2021, ever_37_2021, ever_38_2021)\n\nEverton <- gsub(pattern = \"\\\\W\", replace = \" \", Everton)\nEverton <- gsub(pattern = \"\\\\d\", replace = \" \", Everton)\nEverton <- gsub(pattern = \" t \", replace = \" \", Everton)\nEverton <- gsub(pattern = \" https \", replace = \" \", Everton)\nEverton <- gsub(pattern = \"media\", replace = \" \", Everton)\nEverton <- gsub(pattern = \"read\", replace = \" \", Everton)\nEverton <- tolower(Everton)\nEverton <- removeWords(Everton, stopwords())\nEverton <- stripWhitespace(Everton)\n# Leicester\n\nLeicester <- c(lei_1, lei_2, lei_3, lei_4, lei_5, lei_6, lei_7, lei_1_2021, lei_2_2021, lei_3_2021, lei_4_2021, lei_5_2021, lei_6_2021, lei_7_2021, lei_8_2021, lei_9_2021, lei_10_2021, lei_11_2021, lei_12_2021, lei_13_2021, lei_14_2021, lei_15_2021, lei_16_2021, lei_17_2021, lei_18_2021, lei_19_2021, lei_20_2021, lei_21_2021, lei_22_2021, lei_23_2021, lei_24_2021, lei_25_2021, lei_26_2021, lei_27_2021, lei_28_2021, lei_29_2021, lei_30_2021, lei_31_2021, lei_32_2021, lei_33_2021, lei_34_2021, lei_35_2021, lei_36_2021, lei_37_2021, lei_38_2021)\n\nLeicester <- gsub(pattern = \"\\\\W\", replace = \" \", Leicester)\nLeicester <- gsub(pattern = \"\\\\d\", replace = \" \", Leicester)\nLeicester <- gsub(pattern = \" t \", replace = \" \", Leicester)\nLeicester <- gsub(pattern = \" https \", replace = \" \", Leicester)\nLeicester <- gsub(pattern = \"media\", replace = \" \", Leicester)\nLeicester <- gsub(pattern = \"read\", replace = \" \", Leicester)\nLeicester <- tolower(Leicester)\nLeicester <- removeWords(Leicester, stopwords())\nLeicester <- stripWhitespace(Leicester)\n\n# West Ham\n\nWest_Ham_United <- c(wh_1, wh_2, wh_3, wh_4, wh_5, wh_6, wh_7, wh_1_2021, wh_2_2021, wh_3_2021, wh_4_2021, wh_5_2021, wh_6_2021, wh_7_2021, wh_8_2021, wh_9_2021, wh_10_2021, wh_11_2021, wh_12_2021, wh_13_2021, wh_14_2021, wh_15_2021, wh_16_2021, wh_17_2021, wh_18_2021, wh_19_2021, wh_20_2021, wh_21_2021, wh_22_2021, wh_23_2021, wh_24_2021, wh_25_2021, wh_26_2021, wh_27_2021, wh_28_2021, wh_29_2021, wh_30_2021, wh_31_2021, wh_32_2021, wh_33_2021, wh_34_2021, wh_35_2021)\n\nWest_Ham_United <- gsub(pattern = \"\\\\W\", replace = \" \", West_Ham_United)\nWest_Ham_United <- gsub(pattern = \"\\\\d\", replace = \" \", West_Ham_United)\nWest_Ham_United <- gsub(pattern = \" t \", replace = \" \", West_Ham_United)\nWest_Ham_United <- gsub(pattern = \" https \", replace = \" \", West_Ham_United)\nWest_Ham_United <- gsub(pattern = \"media\", replace = \" \", West_Ham_United)\nWest_Ham_United <- gsub(pattern = \"read\", replace = \" \", West_Ham_United)\nWest_Ham_United <- tolower(West_Ham_United)\nWest_Ham_United <- removeWords(West_Ham_United, stopwords())\nWest_Ham_United <- stripWhitespace(West_Ham_United)\n```\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Preprocessing and merging data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating list of objects to put into the loop\nPrem <- c(\"Arsenal\", \"Manchester_City\", \"Newcastle_United\", \"Everton\", \"Leicester\", \"West_Ham_United\")\n\n# create loop.\nfor (i in 1:length(Prem)){\n \n  # create corpora\n  corpusCall <- paste(Prem[i],\"_corpus <- corpus(\",Prem[i],\")\", sep = \"\")\n    #print(corpusCall)\n  eval(parse(text=corpusCall))\n   #print(corpusCall)\n\n  # change document names for each match to include team name. If you don't do this, the document names will be duplicated and you'll get an error.\n  namesCall <- paste(\"tmpNames <- docnames(\",Prem[i],\"_corpus)\", sep = \"\")\n  eval(parse(text=namesCall))\n  print(namesCall)\n  bindCall <- paste(\"docnames(\",Prem[i],\"_corpus) <- paste(\\\"\",Prem[i],\"\\\", tmpNames, sep = \\\"-\\\")\", sep = \"\")\n  eval(parse(text=bindCall))\n  print(bindCall)\n  # create summary data\n  summaryCall <- paste(Prem[i],\"_summary <- summary(\",Prem[i],\"_corpus)\", sep = \"\")\n  eval(parse(text=summaryCall))\n\n  # add indicator\n  bookCall <- paste(Prem[i],\"_summary$Team <- \\\"\",Prem[i],\"\\\"\", sep = \"\")\n  eval(parse(text=bookCall))\n\n  # add match indicator\n  chapterCall <- paste(Prem[i],\"_summary$Match <- as.numeric(str_extract(\",Prem[i],\"_summary$Text, \\\"[0-9]+\\\"))\", sep = \"\")\n  eval(parse(text=chapterCall))\n\n  # add meta data to each corpus\n  metaCall <- paste(\"docvars(\",Prem[i],\"_corpus) <- \",Prem[i],\"_summary\", sep = \"\")\n  eval(parse(text=metaCall))\n\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"tmpNames <- docnames(Arsenal_corpus)\"\n[1] \"docnames(Arsenal_corpus) <- paste(\\\"Arsenal\\\", tmpNames, sep = \\\"-\\\")\"\n[1] \"tmpNames <- docnames(Manchester_City_corpus)\"\n[1] \"docnames(Manchester_City_corpus) <- paste(\\\"Manchester_City\\\", tmpNames, sep = \\\"-\\\")\"\n[1] \"tmpNames <- docnames(Newcastle_United_corpus)\"\n[1] \"docnames(Newcastle_United_corpus) <- paste(\\\"Newcastle_United\\\", tmpNames, sep = \\\"-\\\")\"\n[1] \"tmpNames <- docnames(Everton_corpus)\"\n[1] \"docnames(Everton_corpus) <- paste(\\\"Everton\\\", tmpNames, sep = \\\"-\\\")\"\n[1] \"tmpNames <- docnames(Leicester_corpus)\"\n[1] \"docnames(Leicester_corpus) <- paste(\\\"Leicester\\\", tmpNames, sep = \\\"-\\\")\"\n[1] \"tmpNames <- docnames(West_Ham_United_corpus)\"\n[1] \"docnames(West_Ham_United_corpus) <- paste(\\\"West_Ham_United\\\", tmpNames, sep = \\\"-\\\")\"\n```\n:::\n\n```{.r .cell-code}\nPrem <- c(Arsenal_corpus, Manchester_City_corpus, Newcastle_United_corpus, Everton_corpus, Leicester_corpus, West_Ham_United_corpus)\n\n\nPrem_dfm <- dfm(tokens(Prem,\nremove_punct = TRUE,\nremove_symbols = TRUE) %>%\ndfm(tolower = TRUE) %>%\ndfm_remove(stopwords('english')))\n\ntopfeatures(Prem_dfm, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   city minutes    goal    ball  league   first    half premier everton    back \n   1762    1367    1207    1194    1185    1125    1034    1003     959     915 \n   time  second    game  united    left    side  corner   right     one    shot \n    874     700     697     684     663     658     592     570     563     561 \n```\n:::\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n# Analysis of merged data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_dfm_tfidf <- dfm_tfidf(Prem_dfm)\n\n# This mostly shows the team names and player names but with the world title it hints at the goal of each team\ntopfeatures(full_dfm_tfidf,50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       city     everton         ham        gray richarlison       watch \n   516.4249    497.8701    233.0097    217.6197    211.8677    208.4639 \n         de   leicester      bruyne   guardiola        west    pickford \n   207.3479    205.8681    200.8701    195.4606    195.0843    189.9960 \n     gordon       villa    maddison   newcastle       bowen       leeds \n   181.9794    175.7092    173.8089    170.9310    169.2040    165.1829 \n      foxes  schmeichel       vardy       foden     arsenal     haaland \n   160.4318    150.7830    142.6866    141.7189    140.9676    140.4310 \n    antonio    brighton    townsend    sterling     chelsea     watford \n   138.8044    136.7146    135.5888    134.9242    134.1237    133.6060 \n     barnes  manchester      palace       jesus   tielemans     hammers \n   132.6387    132.1113    131.4447    130.7281    129.2972    128.5873 \n     wolves   brentford        read     calvert       lewin    bernardo \n   128.5490    127.9489    127.1004    125.2161    125.2161    123.3119 \n  liverpool      united     burnley    benrahma     fornals    goodison \n   122.1510    121.5446    121.4580    119.3028    117.3582    116.1838 \n       saka    doucoure \n   111.5679    110.6451 \n```\n:::\n\n```{.r .cell-code}\nset.seed(1)\n\n# Creating a table to show the highest frequency items and then ranking them\nword_counts <- as.data.frame(sort(colSums(Prem_dfm),dec=T))\ncolnames(word_counts) <- c(\"Frequency\")\nword_counts$Rank <- c(1:ncol(Prem_dfm))\n\nggplot(word_counts, mapping = aes(x = Rank, y = Frequency)) +\n  geom_point() +\n  labs(title = \"Zipf's Law\", x = \"Rank\", y = \"Frequency\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nPrem_smaller_dfm <- dfm_trim(Prem_dfm, min_termfreq = 10)\n\n# trim based on the proportion of documents that the feature appears in; here,\n# the feature needs to appear in more than 10% of documents (chapters)\nPrem_smaller_dfm <- dfm_trim(Prem_smaller_dfm, min_docfreq = 0.1, docfreq_type = \"prop\")\n\ntextplot_wordcloud(Prem_smaller_dfm, min_count = 50,\n                   random_order = FALSE)\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Creating the FCM\n\nPrem_smaller_dfm <- dfm_trim(Prem_dfm, min_termfreq = 20)\nPrem_smaller_dfm <- dfm_trim(Prem_smaller_dfm, min_docfreq = .3, docfreq_type = \"prop\")\n\n# create fcm from dfm\nPrem_smaller_fcm <- fcm(Prem_smaller_dfm)\n\n# check the dimensions (i.e., the number of rows and the number of columnns)\n# of the matrix we created\ndim(Prem_smaller_fcm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 224 224\n```\n:::\n\n```{.r .cell-code}\n# pull the top features\nmyFeatures <- names(topfeatures(Prem_smaller_fcm, 30))\n\n# retain only those top features as part of our matrix\nPrem_smaller_fcm <- fcm_select(Prem_smaller_fcm, pattern = myFeatures, selection = \"keep\")\n\n# compute size weight for vertices in network\nsize <- log(colSums(Prem_smaller_fcm))\n\n# Text plot showing the most popular words\ntextplot_network(Prem_smaller_fcm, vertex_size = size / max(size) * 3)\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n:::\n\n:::\n\n# Sentiment Dictionary\n\nI had orginally wanted to utilize the brand dictionary which looked into competence, ruggedness, sophistication, excitement and sincerity however, the numbers were extremely low and they did not seem to have a very good representation of the text. Due to the lack of information here I decided to focus more in on the sentiment dictionary and talk about the changes that are occurring within it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(599)\n# Testing the sentiment dictionary\nTitles <- c(\"Arsenal\", \"Manchester_City\", \"Newcastle_United\", \"Everton\", \"Leicester\", \"West_Ham_United\")\n\nPrem_tidy <- list(Arsenal, Manchester_City, Newcastle_United, Everton, Leicester, West_Ham_United)\n\nseries <- tibble()\n\nfor(i in seq_along(Titles)) {\n       \n        clean <- tibble(Match = seq_along(Prem_tidy[[i]]),\n                        text = Prem_tidy[[i]]) %>%\n             unnest_tokens(word, text) %>%\n             mutate(Team = Titles[i]) %>%\n             select(Team, everything())\n\n        series <- rbind(series, clean)\n}\n\n# set factor to keep words in order for team and match\nseries$Team <- factor(series$Team, levels = rev(Titles))\n\n# now we start the sentiment analysis with the dictionary nrc\n\nseries %>%\n        right_join(get_sentiments(\"nrc\")) %>%\n        filter(!is.na(sentiment)) %>%\n        count(sentiment, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining, by = \"word\"\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 2\n   sentiment        n\n   <chr>        <int>\n 1 positive     15416\n 2 negative     11238\n 3 trust         7201\n 4 anticipation  6757\n 5 anger         6226\n 6 fear          6139\n 7 sadness       5186\n 8 joy           4148\n 9 surprise      3448\n10 disgust       2410\n```\n:::\n\n```{.r .cell-code}\n#  Breaking it up by every 1000 words to say that is one match and then do a polarity test for each team\nseries %>%\n        group_by(Team) %>%\n        mutate(word_count = 1:n(),\n               index = word_count %/% 450 + 1) %>%\n        inner_join(get_sentiments(\"bing\")) %>%\n        count(Team, index = index , sentiment) %>%\n        ungroup() %>%\n        spread(sentiment, n, fill = 0) %>%\n        mutate(sentiment = positive - negative,\n               Team = factor(Team, levels = Titles)) %>%\n        ggplot(aes(index, sentiment, fill = Team)) +\n          geom_bar(alpha = 0.5, stat = \"identity\", show.legend = FALSE) +\n          facet_wrap(~ Team, ncol = 2, scales = \"free_x\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining, by = \"word\"\n```\n:::\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# testing the other two sentiment packages in tidytext and comparing the differences to get a better feel for the actual sentiment\nafinn <- series %>%\n        group_by(Team) %>%\n        mutate(word_count = 1:n(),\n               index = word_count %/% 450 + 1) %>%\n        inner_join(get_sentiments(\"afinn\")) %>%\n        group_by(Team, index) %>%\n        summarise(sentiment = sum(value)) %>%\n        mutate(method = \"AFINN\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining, by = \"word\"\n`summarise()` has grouped output by 'Team'. You can override using the\n`.groups` argument.\n```\n:::\n\n```{.r .cell-code}\nbing_and_nrc <- bind_rows(series %>%\n                  group_by(Team) %>%\n                  mutate(word_count = 1:n(),\n                         index = word_count %/% 450 + 1) %>%\n                  inner_join(get_sentiments(\"bing\")) %>%\n                  mutate(method = \"Bing\"),\n          series %>%\n                  group_by(Team) %>%\n                  mutate(word_count = 1:n(),\n                         index = word_count %/% 450 + 1) %>%\n                  inner_join(get_sentiments(\"nrc\") %>%\n                                     filter(sentiment %in% c(\"positive\", \"negative\"))) %>%\n                  mutate(method = \"NRC\")) %>%\n        count(Team, method, index = index , sentiment) %>%\n        ungroup() %>%\n        spread(sentiment, n, fill = 0) %>%\n        mutate(sentiment = positive - negative) %>%\n        select(Team, index, method, sentiment)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining, by = \"word\"\nJoining, by = \"word\"\n```\n:::\n\n```{.r .cell-code}\n# Visualization of the 3 different sentiment dictionaries and we can see how the teams compare over the course of the season\nbind_rows(afinn,\n          bing_and_nrc) %>%\n        ungroup() %>%\n        mutate(Team = factor(Team, levels = Titles)) %>%\n  ggplot(aes(index, sentiment, fill = method)) +\n  geom_bar(alpha = 0.8, stat = \"identity\", show.legend = FALSE) +\n  facet_grid(Team ~ method)\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Here we can see that premier is skewing it more towards being positive as that is simply the name of the league\nbing_word_counts <- series %>%\n  inner_join(get_sentiments(\"bing\")) %>%\n  count(word, sentiment, sort = TRUE) %>%\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining, by = \"word\"\n```\n:::\n\n```{.r .cell-code}\n# Removing premier from the analysis since it is incorrect\nbing_word_counts <- bing_word_counts %>%\n  filter(!row_number() %in% c(1))\n\nbing_word_counts %>%\n        group_by(sentiment) %>%\n        top_n(10) %>%\n        ggplot(aes(reorder(word, n), n, fill = sentiment)) +\n          geom_bar(alpha = 0.8, stat = \"identity\", show.legend = FALSE) +\n          facet_wrap(~sentiment, scales = \"free_y\") +\n          labs(y = \"Contribution to sentiment\", x = NULL) +\n          coord_flip()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nSelecting by n\n```\n:::\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n```{.r .cell-code}\nbing_and_nrc %>%\n  select(Team, method, sentiment) %>%\n  filter(method == 'Bing')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 355 × 3\n   Team            method sentiment\n   <fct>           <chr>      <dbl>\n 1 West_Ham_United Bing           2\n 2 West_Ham_United Bing           1\n 3 West_Ham_United Bing           1\n 4 West_Ham_United Bing          -4\n 5 West_Ham_United Bing          -1\n 6 West_Ham_United Bing          -6\n 7 West_Ham_United Bing          20\n 8 West_Ham_United Bing          22\n 9 West_Ham_United Bing           8\n10 West_Ham_United Bing          13\n# … with 345 more rows\n```\n:::\n:::\n\n\n# Research question\n\nAnswering the research questions.\n\n::: {.callout-note collapse=\"true\"}\n## Word count changes\n\n1.  What was the average word count for each team?\n\nThe average word count for each team is as follows in descending order:\n\nEverton = 1491\n\nManchester city = 1439\n\nArsenal = 1343\n\nLeicester = 1064\n\nWestHam = 856\n\nNewcastle united = 664\n\nWhen we are comparing these numbers we notice some interesting things and that is that the top two teams of Manchester city and arsenal are not the teams with the most words as I thought they would be. But instead, Everton has taken the top spot by roughly 60 tokens. Another interesting point is that that 3 of the teams seem to be in the same area then there is a the middle holder of Leicester and then it drastically drops down to the last two teams. Another fun point to note is that the team with the lowest amount of mean tokens is not the team that performs the worst and they usually finish about the middle of the pack. I wonder why these teams have such a large difference between their numbers.\n\n2.  Does the word count increase or decrease over the season?\n\nThe change seems to be both an increase and decrease over the season which I hypothesis is the cause of the change in performance however, there are other factors that could be impacting this such as less dramatic events happening resulting in less words.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# had to set this to inf since it would only show 100 documents and I wanted the summary data of everything\nPrem_summary <- summary(Prem, n = Inf)\n\nPremier_df <- data.frame(Prem_summary)\n\n# creating the mean tokens for each team\nPremier_df %>%\n  group_by(Team) %>%\n  summarise(mean_tokens=mean(Tokens),\n            .groups = 'drop')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  Team             mean_tokens\n  <chr>                  <dbl>\n1 Arsenal                 352.\n2 Everton                 870.\n3 Leicester               595.\n4 Manchester_City         815.\n5 Newcastle_United        385.\n6 West_Ham_United         498.\n```\n:::\n\n```{.r .cell-code}\n# calculating the change over time in tokens\n\nPremier_df_short <- Premier_df %>%\n  slice(which(row_number() %% 8 == 1))\n\nStart_tokens <- Premier_df_short[1,c(\"Tokens\")]\n\n  Token_change <- Premier_df_short %>%\n  group_by(Team) %>%\n  dplyr::mutate(Previous = lag(Tokens),\n                Next_token = lead(Tokens),\n                Token_diff = Tokens - Previous,\n                Percent_token_diff = (Token_diff/Previous)* 100,\n                Percent_change_token = (Token_diff/lag(Tokens) -1) * 100,\n                TChange_from_token_one = (Tokens/Start_tokens - 1) * 100)\n\n# visualization of the token change over the season\nggplot(data = Token_change) +\n  geom_col(aes(x = Match, y = Percent_token_diff, fill = Percent_token_diff > 0, width = 4), alpha = .2) +\n  geom_text(aes(x = Match, y = Percent_token_diff, label = paste0(round(Percent_token_diff,2), \"%\")),size = 3, vjust = -.5) +\n   theme_fivethirtyeight(base_size = 10, base_family = 'serif') +\n  theme(axis.title = element_text(family = 'serif', size = 15)) + ylab('Percent Changed') + xlab('Matches') +\n  labs(title = \"Token change over season [%]\", caption = \"8 Match gaps\") +\n  facet_wrap(~Team) +\n  expand_limits(y = 210)\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Sentiment changes\n\n1.  What is the overall sentiment for each team?\n\nThe over arching sentiment seems to be mostly positive however, besides the top two teams the other teams do have the occasional deep into the negative sentiment which I found very interesting. This is related to performance and the top teams naturally have more positive things to say when their team is performing and winning games. However, the lower in the table the team the more like they are to use negative words and visualized above.\n\n-   Does it grow more positive or negative over the season\n\nWhen looking at the sentiment change over the course of the season we notice some interesting things. The first thing that stands out the most to me is the consistency of the sentiment for each team and the top 2 teams Arsenal and Manchester city have a very consistent sentiment with changes not exceeding 100%(over 8 match gaps). The other teams see at least 1 sentiment change over the course of the season that exceeds 500% which is a huge jump and this could be the culmination of a losing streak or winning streak. I hypothesis that this is more likely to happen for the teams at the bottom of the table and the team that is just outside of the top teams. This is very interesting since the lower table teams make more sense as they are more likely to have a losing streak or the wins tend to have a larger impact on their overall season but the teams that are just outside of the top teams they have a differnt level of impact. This impact is driven by just being outside of the top of table and this make every point that much more important and thus they tend to use more words than the lower table teams while also using more sentiment driven words as it means more to them. The two teams that are just outside of the top of the table are new castle and everton and leicester has been pushing that realm lately as well. When looking at the visualization of sentiment change we notice how new castle and everton have very sharp jumps in their sentiment whether it is going down by 500% or it is going up 580%. This shows how each match has a large impact on them. But the real interesting matter is Leicester which around the 20 match mark they go down 2000% sentiment. I am very interested into looking into this matter and figuring out what happened here.\n\n-   What is the most positive moment?\n\nMost positive sentiment for each team\n\nManchester City - 131\n\nArsenal - 129\n\nEverton - 83\n\nWest Ham United - 71\n\nLeicester - 60\n\nNew castle united - 58\n\nWhen looking at the max sentiment levels we notice that both Arsenal and Manchester city stand at the most positive end of the spectrum with a sentiment score of 131. I assume this is largely due to the fact that they tend to win more games and have longer win streaks thus increasing the odds of positive words being used. Another factor is that more words are typically being used with these team compared to some of the other ones and this can reduce the impact of those negative words if it flooded with positive words. The teams that have the higher sentiment scores are the ones that usually use more words when talking about the matches. Now that we know where the highest sentiment scores are lets take a deeper look into what is actually happening to causes these results.\n\n-   What has caused it to be positive? Did they win a match or a derby?\n\nWhen looking into the matches we notice some interesting things. They will be described below:\n\nArsenal - (Match 27) When looking into the most positive moment in Arsenal it is when they entered the top 4 with a big win against West Ham united. The top 4 is a big deal in the premier league as they are the 4 teams that will be allowed to compete in the champions league the following season which decides the best club soccer team. This also means that you are a strong contender in the race for the premier league title and that is something that has eluded Arsenal for a very long time. In fact, they have not finished in the top 4 since the 2016/2017 season. For a top tier team this is a long time and thus, the importance of them making the top 4 again was a major moment for them. This document starts out with a very positive line which is, \"goals from Gabriel Martinelli and Emile Smith Rowe wrapped up an impressive win against West Ham United\" This shows a peak at how well the team performed this game and this justifies the high level of excitement and positive words used in this document.\n\nManchester city - (Match 33) When looking into this match we see that Manchester city puts on a world class match against Norwich with numerous players playing exceptionally well. To highlight one would be Raheem Sterling where he won man of the match with a hat-trick. A hat-trick is where you score three goals within a match and this is a very impressive feat however, this was not the only thing that happened during this match that made it a positive experience. The other impact was that \"there was a notable milestone for Pep Guardiola, who celebrated the 550th win of his management career\". This is a huge achievement and this followed by the major win for Manchester city we were delivered a high moment for the season which surprisingly was more positive compared to when they won the league.\n\nNewcastle United - (Match 31) Has the lowest positive sentiment score out of all of the teams so I am expecting a different type of review here. When looking into the match we notice that they actually drew this match 1-1 to Westham United however, there were some key points that made this more positive which is Willock got his first goal of the season for Newcastle and this draw was a \"vital point and extended their unbeaten run to six Premier League games\". This shows that this was extremely important for them to keep the morale of the team high while earning some points to move forward. This was an important match for them but as we know the sentiment score only reached 58 which seems justified by this document.\n\nEverton - (Match 11) This document starts off with, \"Six minutes. Or 379 seconds. That was all it took for Everton to not only rescue a losing position but convert it into an all-but guaranteed three points\". This shows that it was a very intense match against Burnley. Burnley opened up with the scoring in the 53rd minute which put Everton down which, \"came as a surprise because Everton appeared to have suffocated opponents who created a handful of chances in the opening half\". Everton knew that Burnley was a strong team when they are ahead however, Everton only needed 7 minutes to return this match to 1-1. Shortly after EVerton score 2 goals in the 65th and 66th minute which insane on its own. However, with this win Everton climbed to the top of the table for the time being and this was a major win for them.\n\nWestham United - (Match 11) This document was another comeback story that launched them forward in the league. They were playing against Leeds United and Leeds opened up the scoring in the 20th minute putting the West ham side playing to catch up. However, this came true in the 67th minute where Leeds scored an own goal to tie the match up and leaving plenty of time to turn this into a win. West ham did just that in the 90th minute which is almost the end of the game we are getting into extra time. \"90th minute Antonio winner to claim the three points.The victory sees David Moyes side climb to seventh in the Premier League table after just six games\". This line from the document shows the importance of this match.\n\nLeicester - (Match 10) \"It nonetheless took Leicester just eight minutes to take the lead with Portugal full-back Ricardo Pereira winning possession and then galloping down the right channel with frightening pace\". We see an opening goal for Leicester to start them off on a very positive moment. Norwich score a later first half goal in the 44th minute to make this game even however, this did not stop the leicester side as they come back in the 76 minute to make it 2-1 which is how the game ends. This let Leicester climb to the 8th spot in the table and this is big since a loss or draw here could have easily dropped them sub-10th which puts the pressure on them.\n\nSome interesting patterns here we notice that the top teams seem to have their higher sentiment moments later in the season where as the lower league teams tend to have them earlier on. The top table team wins are ones that put them in a good spot to win the league where as the lower table teams highest moments tend to be these comeback wins that put them just above the middle of the table. Now lets take a look at the most negative moments. \\* What is the most negative moment?\n\nThe lowest sentiment for each team is as follows:\n\nArsenal - 3\n\nManchester City - 18\n\nEverton - -24\n\nWest Ham United - 0\n\nLeicester - -2\n\nNew castle United - -24\n\nWhat we notice here is that the top two teams never go negative however, one of the top 3 positive sentiment scores was Everton and it actually has the lowest sentiment score reached. I am very curious to take a deeper look into their season and see what has caused them to have such extremities.\n\n-   What is causing these low moments?\n\nArsenal - (Match 48) This is the very last match of the 2021 season and Arsenal played an extremely good match against Everton where they scored 5. However, the reason this match is such a low score is that even with this strong win they fell to 5th place while their rivals took the 4th spot to move on to the champions league. As an Arsenal fan myself this was a real heartbreaking moment for us.\n\nManchester City - (Match 7) This match was a win for Manchester city against the Wolves however, this was the match where Queen Elizabeth passed away and there was the moment of silence for her. I believe this extremely sad news is what caused a very strong match for Manchester city to be dropped to a lower score.\n\nNewcastle United - (Match 23) Newcastles lowest match was a 3-1 loss vs Liverpool a very strong team. \"Newcastle fought hard and could have had a penalty when Trent Alexander-Arnold appeared to fell Fraser in the second half, but in the end it was a moment of quality from the Liverpool full back three minutes from time which made sure of the victory for the hosts\". Newcastle played hard but was overwhelmed by their opponents and the calls did not seem to favor them as a penalty was passed. An early goal pushed the liver pool team ahead and there was also a very later goal in the 87th minute that finish the game out.\n\nEverton - (Match 2) Everton lost this match against Villa and by this point they have yet to collect any points in the season leaving them at the bottom of the table. \"Everton must wait another week, at least, to collect their opening points of this Premier League campaign\". The result ended 2-1 where there were two late goals 1 for villa in the 86th minutes and 1 for Everton in the 87th minute. However, this goal was not enough for them to collect anything here and they fell 2-1.\n\nWest ham United - (Match 27) West ham had a 1-0 loss vs Manchester United with a very late goal. \" Marcus Rashford scored for Manchester United with virtually the last kick of the game to break West Ham United hearts at Old Trafford\". There were a lot of big chances for each team which makes the west ham loss all the worse since they were fitting for a win here. \"Bowen's industry earned the No20 a corner off Telles and, whipping it towards the far post, Souček got across his man and flicked towards the far post - agonizingly wide, as it turned out, with Antonio also sliding in.Areola then got down low to deny Ronaldo on the swivel and hold, before Rice concerned de Gea with a deflected low cross - just wide of his near post.As football so often provides, there was to be one, final, cruel twist, Rashford's goal snatching all three points at the death for the Red Devils\". Here is the major sentence that shows the emotions of the match.\n\nLeicester - (Match 3) \"The frustration was about to grow even further. When James Ward-Prowse fizzed a cross into the box, there was Adams to acrobatically volley past Ward. 2-1 to the visitors, with six minutes of normal time to go. That early optimism was gone\". Leicester also had a close loss and this one also came in the closing minutes of the game to drive a crushing blow. This left Leicester in 18th place and if they were to finish here they would be dropped from the league.\n\nThere are some interesting patterns going on here one being a lot of these negative sentiment moments is caused by a last minute goal for the other team that has results in a loss. This makes sense as nothing is more crushing then playing the full 90 minutes just to loss all points in the last minute.\n\n-   What is the sentiment range for each team?\n\nArsenal is showing the largest range which is expected since they have touched the top of the table just to have it pulled away in the closing games of the season. Manchester city has the second largest range which shows the top teams have the largest range out of the teams. This is interesting as I expected the middle teams to have the largest range as they experience both aspect of the season.\n\nArsenal range 3-129 = 126\n\nManchester city range 18 - 131 = 113\n\nNew castle range -24 - 58 = 82\n\nWest Ham range 0 - 71 = 71\n\nEverton -24 - 83 = 107\n\nLeicester -2 - 60 = 62\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# were they more positive or negative over time\n\nafinn_shorter <- afinn %>%\n  slice(which(row_number() %% 8 == 1))\n\nStart_sentiment <- afinn_shorter[1,c(\"sentiment\")]\n\nSentiment_change <- afinn_shorter %>%\n  group_by(Team) %>%\n  dplyr::mutate(Previous = lag(sentiment),\n                Next_sentiment = lead(sentiment),\n                sentiment_diff = sentiment - Previous,\n                Percent_sentiment_diff = (sentiment_diff/Previous)* 100,\n                Percent_change_sentiment = (sentiment_diff/lag(sentiment) -1) * 100,\n                Change_from_sentiment_one = (sentiment/Start_sentiment - 1) * 100)\n\n# Sentiment change over the season\n\nggplot(data = Sentiment_change) +\n  geom_col(aes(x = index, y = Percent_sentiment_diff, fill = Percent_sentiment_diff > 0), alpha = .2) +\n  geom_text(aes(x = index, y = Percent_sentiment_diff, label = paste0(round(Percent_sentiment_diff,2), \"%\")),size = 2, vjust = -.5) +\n   theme_fivethirtyeight(base_size = 10, base_family = 'serif') +\n  theme(axis.title = element_text(family = 'serif', size = 15)) + ylab('Percent Changed') + xlab('Matches') +\n  labs(title = \"sentiment change over season [%]\", caption = \"10 Match gaps\") +\n  facet_wrap(~Team) +\n  expand_limits(y = 250)\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Here we can see the most positive and negative sentiment values for each team\nmax_sentiment <- afinn %>%\n  group_by(Team) %>%\n  summarise(Max_sentiments=max(sentiment),\n            .groups = 'drop')\n\nmin_sentiment <- afinn %>%\n  group_by(Team) %>%\n  summarise(Min_sentiments=min(sentiment),\n            .groups = 'drop')\n```\n:::\n\n:::\n\n# LDA Model\n\nTopic modeling is utilized to pull out topics from a set of documents in my case it is 271 documents with roughly 1000 tokens per document. Topics are a cluster of similar words that are pushed into separate topics and this can help us understand the hidden meaning. The size of the bubble correlates to the frequency of the topic in the documents. The distance shows the semantic relationship between the topics. Now on the right the blue bar shows the frequency of the word in a given topic and the red will show the estimated frequency\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(9098)\n\nPrem_df <- data.frame(text = sapply(Prem, as.character), stringsAsFactors = FALSE)\n# The reason I am selecting 162 is because that is 60% of the original version and I want to use this as my training model to predict on the rest of the 40%\n\n# creates string of combined lowercased words\ntokens <- tolower(Prem_df$text[1:162])\n\n# performs tokenization\ntokens <- word_tokenizer(tokens)\n\n# iterates over each token\nit <- itoken(tokens, Match = Prem_tibble$Match, progressbar = FALSE)\n\n# built the vocabulary\nv <- create_vocabulary(it)\n\nv <- prune_vocabulary(v, term_count_min = 10, doc_proportion_max = 0.2)\n\n# check dimensions\ndim(v)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1183    3\n```\n:::\n\n```{.r .cell-code}\n# creates a closure that helps transform list of tokens into vector space\nvectorizer <- vocab_vectorizer(v)\n\ndtm <- create_dtm(it, vectorizer, type = \"dgTMatrix\")\n\nlda_model <- LDA$new(n_topics = 6, doc_topic_prior = 0.1,\n                     topic_word_prior = 0.01)\n\ndoc_topic_distr <- \n  lda_model$fit_transform(x = dtm, n_iter = 1000,\n                          convergence_tol = 0.001, n_check_convergence = 25,\n                          progressbar = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nINFO  [19:54:23.923] early stopping at 150 iteration\nINFO  [19:54:24.061] early stopping at 50 iteration\n```\n:::\n\n```{.r .cell-code}\nbarplot(doc_topic_distr[1, ], xlab = \"topic\",\n        ylab = \"proportion\", ylim = c(0,1),\n        names.arg = 1:ncol(doc_topic_distr))\n```\n\n::: {.cell-output-display}\n![](TextAnalysis_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\nlda_model$get_top_words(n = 6, topic_number = c(1L, 3L, 6L),\n                        lambda = .3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1]        [,2]      [,3]     \n[1,] \"ham\"       \"villa\"   \"palace\" \n[2,] \"lacazette\" \"com\"     \"haaland\"\n[3,] \"rowe\"      \"mancity\" \"norwich\"\n[4,] \"debut\"     \"width\"   \"many\"   \n[5,] \"xhaka\"     \"www\"     \"today\"  \n[6,] \"cup\"       \"meta\"    \"wins\"   \n```\n:::\n\n```{.r .cell-code}\nit2 <- itoken(Prem_df$text[163:271], tolower,\n              word_tokenizer, ids = Prem_df$Match[163:271])\n# creating new DFM\nnew_dtm <- create_dtm(it2, vectorizer, type = \"dgTMatrix\")\n\nnew_doc_topiic_distr = lda_model$transform(new_dtm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nINFO  [19:54:24.172] early stopping at 20 iteration\n```\n:::\n\n```{.r .cell-code}\nperplexity(new_dtm, topic_word_distribution = lda_model$topic_word_distribution,\n           doc_topic_distribution = new_doc_topiic_distr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 878.86\n```\n:::\n:::\n\n\n[LDA Model](http://127.0.0.1:7488/#topic=0&lambda=1&term= \"LDA Model\")\n\n# Conclusion\n\n**Were the research questions answered?**\n\nYes, I believe we found some answers to the question that were being asked\n\n::: {.callout-note collapse=\"true\"}\n## Does Premier League soccer teams language change over the course of the season?\n\nYes, there appears to be a language change over the season when analyzing the data. When are able to identify these with:\n\n-   The token count change over the season and how it is different for each team.\n    -   Top two teams seem to be very aligned while the other ones tend to be more sporadic.\n    -   We also notice that the higher ranked the team the more likely they are to use more words.\n-   The sentiment analysis change over the season for each team.\n    -   We notice that the top two teams seem to be consistent once more and that there is not large jumps for them. We also notice that their high sentiment comes later in the season.\n    -   The other 4 teams seem to be less consistent and have very large extreme changes both negative and positive and this highlights how language changes over the season. They also tend to have their high moments earlier in the season.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Does the language change in relation to the success of the season?\n\nYes, there appears to be a relationship between language and success of the season. We notice this with:\n\n-   The sentiment is very different compared between the top two teams and the other 4 teams. When looking at this we notice the top teams stay positive regardless of the match in the season and never dip below that line while the other teams have dipped below it numerous times. This is related to the success of the season and wins and losses. '\n\n-   We also notice how the teams that are winning more matches tend to use more words with the exception of Everton which uses the most words despite not being in the top 2 teams. Between these two facts we are able to say that yes, there is a relationship between these two variables.\n:::\n\n# Bibliography\n\n-   City, M. (2022). NEWS. Retrieved from Mancity: https://www.mancity.com/news/mens\n\n-   Club, L. F. (2022). First Team. Retrieved from Leicester Football Club: https://www.lcfc.com/matches/reports\n\n-   Club, T. A. (2022). NEWS. Retrieved from Arsenal: https://www.arsenal.com/news?field_article_arsenal_team_value=men&revision_information=&page=1\n\n-   Everton. (2022). Results. Retrieved from Everton: https://www.evertonfc.com/results\n\n-   United, N. (2022). Our Results. Retrieved from Newcastle United: https://www.nufc.co.uk/matches/first-team/#results\n\n-   United, W. H. (2022). Fixtures. Retrieved from West Ham United: https://www.whufc.com/fixture/list/713\n:::",
    "supporting": [
      "TextAnalysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}